// import type { Metadata } from "next";
//@ts-nocheck


import "./globals.css";
import Header from "@/components/Header";
import { createContext, useState } from "react";
import Themecontext from "@/components/theme";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}) {
  
  return (
    <html lang="en">
      <body
       
      >
       <Themecontext children={children}/>
      </body>
    </html>
  );
}
